Repository GSG-FC02/real-estate-wibsite-6, pull requests merged in 2021-03, with the labels that each got.

#4 writing html and css code for footer in home page
  index.html
  style.css
Labels: approved

#7 Adding Profile picture and a search bar
  index.html
  real-estate-agent-with-house-model-keys.jpg
  style.css
Labels: approved

#2 writing the code of services section
  index.html
  neighborhood.png
  rent.png
  style.css
Labels: request-change

#11 create html and style css files for sing in page
  index.html
  login.html
  neighborhood.png
  real-estate-agent-with-house-model-keys.jpg
  rent.png
  style.css
Labels: awaiting-review

#14 Creating about us page
  AboutUs.html
  style.css
Labels: awaiting-review

#16 contact us page
  contact-us-12.jpg
  contact1.html
  style.css
Labels: awaiting-review

#17 Sing up
  login.html
  style.css
Labels: awaiting-review

#19 the last edit
  contact1.html
  style.css
Labels: approved

#8 Writing html and css code for hrader in home page
  .gitignore
  AboutUs.html
  Buy&Rent.css
  Buy&Rent.html
  contact1.html
  home1.jfif
  home2.jfif
  home3.jfif
  home4.jfif
  home5.jfif
  home6.jfif
  index.html
  login.html
  logo.png
  style.css
Labels: approved
